apiVersion: v1
kind: Secret
metadata:
  name: docker-container-registry
  namespace: own-app
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"ghcr.io":{"username":"dotkuro","password":"${DOCKER_SECRET}"}}}