name: deploy

on: pull_request

jobs:
  deploy-test-app:
    name: Deploy test app
    runs-on: ubuntu-latest
    steps:
      - name: checkout out the repository
        uses: actions/checkout@v2
      - name: install kubectl
        uses: azure/setup-kubectl@v3
      - name: setup kubectl
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - name: deploy manifest
        run: |
          kubectl apply -f manifests/test-app.yaml
      - name: verify deployment
        run: |
          kubectl --namespace 'test-app' rollout status 'deployment/test-app'
